### ISSUE TITLE
Cannot read properties of undefined (reading 'initialState')

### ISSUE THREAD

**Issue by torrfura** [wobsoriano/svelte-clerk#99]
We get this from time to time:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initialState')
	in ClerkProvider.svelte
	in context.svelte 
	
	const ctx = useClerkContext();
``` 

Current solution is to clear all cookies and make a hard refresh. Not super-critical, but happends from time to time in development.

**Comment by wobsoriano** [comment]
Please update to latest version, and feel free to reopen this issue if you still have the problem.

Thanks!
